---
title: "Introduction to the atmospheric Package"
author: "Dan Kelley (https://orcid.org/0000-0001-7808-5911)"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
    fig_caption: yes
    fig_width: 7
    fig_height: 5
    dpi: 72
    dev.args: list(pointsize=11)
vignette: >
  %\VignetteIndexEntry{Introduction to the atmospheric Package}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  markdown:
    wrap: 72
---


```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

**Abstract.** This shows how to plot a recent atmospheric sounding at the
default location, Shearwater, Nova Scotia, Canada.


# Plot the most recent sounding for Shearwater, Nova Scotia, Canada.


This downloads the most recent sounding. Note the use of `try()`, to avoid an
error if the server (reference 1) cannot supply the file via the constructed
URL (reference 2).

```{r, echo = TRUE}
library(atmosphere)
dayOffsets <- seq(-2, -1)
soundingFile <- try(downloadAtmosphericSounding())
if (!inherits(soundingFile, "try-error")) {
    par(mar = c(3, 3, 1, 1), mgp = c(2, 0.7, 0))
    sounding <- readAtmosphericSounding(soundingFile)
    plotAtmosphericSounding(sounding)
    unlink(soundingFile)
}
```

# References

1. <https://weather.uwyo.edu/upperair/sounding.html>
2. <https://weather.uwyo.edu/cgi-bin/sounding?region=naconf&TYPE=TEXT%3ALIST&YEAR=2024&MONTH=07&FROM=1012&TO=1012&STNM=73110>
